travis:
  secure:
    BINSTAR_TOKEN: kFbeIvrJAcQG86XHDelTe+92TK1HBq9xLjHlUKSCE9N2QsCJCF3cfSOonjsQJg23ZqakDHND+PnOAhoqeZLGIRTifbFltd5FFg5oStfvWPKzX0T8NifQzFDLRqd7Iv2TcrsWll8ucL068R5x8w96SgVtOy6MGCGEylgNUQexVgUmMmu1DYr2yNx91oxU2uSjFmkeTMe36ymKYgSK2NqOyw5TKgu08zW5zrVlxSPrWx83I6Ut05ZdGS19Cva32/R9WEKSZmlD/v84P8ClwoeP+qmdud07wOmuHOsWQeciFdIfUesoTH8AOZ2pBThPNcqX9jg5DlRRF/2pjhw9CnEfKpmVhfBd0/G3MVX2c9O1YED8nwaX31bs5skAW9HJoxyBgcxziB0WID/k2zGlG+D7NR3cHRWSD41LDp31zHMNh5YqmTlFH8LB7AhAiL691DaPv0MjFIaKHl4EX1WXldbj2SUzroZGiTEaW/YBdUlpFhiCY1/VBQ70yTcqaXElfcY+3hZW2FntMsGOvKeMF1GNHOKK0rL7hdhyphK1+trgs4lRKgd7fQQuYw+iJyaxOPWInbjKRC5CefQoZD4midku5eeiIzEbkKRqFjx3AXTLG7/F/cfvMvhqHPk6ctXwWfTXPlHIoFZkZi/G1m4UTFjnTjwP4+nyZniHo6CKj8X81Tc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
